#-------------------------------------------Pre Lab 4-----------------------------------------------#
rm(list=ls(all=TRUE))
library(SDSFoundations)
acl <- AustinCityLimits


#---------------------------------------- Reflect on the question ------------------------------------------
#1
#a. How many artists are in this dataset?
dim(acl)

#b. How many of the first 10 artists in the dataset were Grammy winners?
sum(acl[1:10,]$Grammy == 'Y')

#c) What genre was played by the first female artist in the dataset who was over 60 years of age? Match the case of the genre as it appears in the dataset.
acl[acl$Gender=='F' & acl$Age > 60,][1,]$Genre


#1) How many columns will be present in the table generated by the following line of code?  
gender <- table(acl$Gender)
gender



# Create contingency table 
twoway <- table(older$Gender,older$Genre)
twoway

#What would the code look like if we wanted to keep the legend but stack the bars (instead of set them side-by-side)?
# Visualize the counts
barplot(twoway, legend=TRUE, beside=TRUE)


#---------------------------------------- Analyze the Data ------------------------------------------

#1a. How many male artists are in the 30+ year old artist subset of the Austin City Limits dataset?

head(acl)
nrow(acl[acl$Gender=='M' & acl$Age > 30,])

#b
nrow(acl[acl$Gender=='F' & acl$Age > 30,])

#2a. To determine the proportion of jazz performers that were male, you would divide ________ by ________. (Enter responses in the order listed in the quesiton.)

Age30 <- acl[acl$Age > 30,]
table(Age30$Gender,Age30$Genre)

#b. To determine the proportion of males that performed jazz, you would divide ________ by ________. (Enter responses in the order listed in the quesiton.)
table(Age30$Gender,Age30$Genre)



#3b. How many artists performed rock/folk/indie music?
#Subset the data for artists age 30 or older
older <-acl[acl$Age>=30,]

# Create tables of marginal distributions
genre <- table(older$Genre)
genre
gender <- table(older$Gender)
gender

#4b. What is the probability that a randomly selected artist from the dataset performed rock/folk/indie music?
prop.table(genre)

#5b. What is the probability that a randomly selected female artist performed rock/folk/indie music?
prop.table(twoway,1)




